### ISSUE TITLE
Questions on Basil.js

### ISSUE THREAD

**Issue by fabiantheblind** [basiljs/basil.js#33]
Here there guys. I've been working with Basil for the last month and I was thinking of incorporating it deeper into my next seminar. I have some questions though:  

- How do I disable the error handling? It is great for beginners to not have the std ID error messages but to pinpoint problems it makes it harder. 
-  How do you test new features before merging them into master? It would be great to have some guidance for developers. 
- Is there a roadmap for basil? Where is it heading?
- Are you still using it in your curriculum?

Last but not least. You did a awesome job with it. 👍 Great work.

**Comment by ludzeller** [comment]
Hello Fabian,

Great to hear that you like basil.js so much and that you would like to teach it in you class. That's the Interface Design course at FH Potsdam, right?

Regarding the error handling... The others might know more, but I think it's not configurable. Or could you elaborate a bit more on what you dislike and how you imagine it to be?

We have a set of automatic tests that we definitely run very often. And we use our gut feeling. Again, maybe I didn't fully get your question... :) Besides the tests there is no strong protocol to follow, just be careful and always think in the perspective of programming beginners. We take them seriously.

Our roadmap is quite simple... we as the existing members are currently not planning to extend basil.js further. We have the feeling that we reached a solid spot where the most essential features are already present and that the InDesign (JavaScript) engine has limits that prevent e.g. a fast real-time mode. 

But we are still using it in our seminars and will immediately fix it, if Adobe updates break it. But  it's currently not as intense as it obviously had to be when we developed it. For three semesters around 2013 we had been very busy incorporating it in our seminars, also to find the time to build it and test it in real-life  teaching. Right now, it's more living as a side option, so we do not focus full seminars on it but rather teach it together with Processing (obviously) as a side option for generative print.

But we are always open for new ideas and contributors! And other lecturers who want to do classes about it. So, if you need any basil.js help for preparing your class, please let us know!

**Comment by trych** [comment]
Hi Fabian,
great to see that there is some stuff going on with basil.js still. I was also teaching basil.js in a brief introduction seminar two semesters ago (at HAW Hamburg) and the idea is to continue with this next semester.

I recently also collected a few ideas for additions and improvements to basil.js and was looking, if I could implement them myself at some point, but as I just finished my Bachelor thesis (making heavy use of InDesign scripting of course ;) ), I did not find the time yet, to post my ideas here in an organized manner. I will hopefully get around to that in the next weeks.

Looking forward to bringing the project forward!
Timo

**Comment by fabiantheblind** [comment]
Hi Ludwig, hi Timo,

>Great to hear that you like basil.js so much and that you would like to teach it in you class. That's the Interface Design course at FH Potsdam, right?

Yes it is here at the FH-Potsdam. I already used it for a 4CP seminar this semester and would like to extend this in a full seminar.  

>Regarding the error handling... The others might know more, but I think it's not configurable. Or could you elaborate a bit more on what you dislike and how you imagine it to be?

I would love to have some global flag for Basil that enables/disables the error handling. So InDesign throws the raw error.  

Something like (in file basil.js):  

    pub.DEBUG = true;

or

    pub.errorHandling = false;

It would help to learn more about Basil and to find errors in my own code.

>We have a set of automatic tests that we definitely run very often. And we use our gut feeling. Again, maybe I didn't fully get your question... :) Besides the tests there is no strong protocol to follow, just be careful and always think in the perspective of programming beginners. We take them seriously.

It would be nice to know

- how to run the automated tests. (run ./basil.js/test/all-test.jsx I think)
- what it needs to write own test (something like a test.example.jsx)
- How to interpret the test results

>Our roadmap is quite simple... we as the existing members are currently not planning to extend basil.js further. We have the feeling that we reached a solid spot where the most essential features are already present and that the InDesign (JavaScript) engine has limits that prevent e.g. a fast real-time mode.

Okay. good to know.  

>But we are always open for new ideas and contributors! And other lecturers who want to do classes about it. So, if you need any basil.js help for preparing your class, please let us know!

That's why I asked about the testing and all that. If I would start writing some feature, it would be best to do it the "Basil" way. It would be good to know where to hook in.

Currently, from reading the code, I think it would be something like:  

    
in ./basil.js/includes/coolfeature.js

    pub.thing = function (args){
        // do something
    }


in ./basil.js/basil.js

    // after #include 'includes/core.js'
    #include 'includes/coolfeature.js'

But what about things like:

- function structure?
- utility functions? (Where to put them)
- indent? (tab or spaces? 2 or for spaces)
- quotes (single or double)
- comment styling and doc generation (yuidoc)  

I know this is not trivial but some guidance on things like that would be great. If not in an "oneshot" effort maybe when/if I actually create a new feature.  

Cheers
Fabian

----

Some resources for making this accessible for contributors are e.g.

- [help.github.com || Helping people contribute to your project](https://help.github.com/articles/helping-people-contribute-to-your-project/) (in short? add a folder called .github to the root of the repo. Add 3 files CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md. These will be parsed when creating issues and PRs and can be linked in the main README.md)  
- adding some kind of linting rules. e.g eslint
- adding some kind of codeformatting rules (didn't find a tool that is suitable right now)

**Comment by trych** [comment]
There is actually a bit about coding style in the Wiki: https://github.com/basiljs/basil.js/wiki

But I also think, it would be nice for new developers (like I hope to become one) to have it a bit more detailed. But then, I think it is also up to us (the new developers) to ask specific questions that could be step by step incorporated into this wiki. So I guess Fabian has just started that process. I will add more questions as soon as I find the time.

Cheers, Timo

**Comment by fabiantheblind** [comment]
Ah. cool. Thanks.

**Comment by b-g** [comment]
Hi @fabiantheblind,

Many thanks for the input and the push!

Yes, it would be cool to have all this! 

RE: Code Style
I think an .editorconfig like this [one](https://github.com/generative-design/Code-Package-p5.js/blob/master/.editorconfig) should to the trick

RE: Better debugging

Instead of 
```
pub.DEBUG = true;
pub.errorHandling = true;
```
I would rather see it as an optional parameter of [b.go()](http://basiljs.ch/reference/#go) ... maybe something like
```
b.go(b.MODEVISIBLE, {debug:true})
```

Best,
B

**Comment by fabiantheblind** [comment]
Hi @b-g 

maybe starting with .editorconfig is simpler. The changes that would be introduced by eslint (in #34 ) would be massive.  

About the debugging. I tried finding a point to hook in but did not see it. Any hints?

**Comment by b-g** [comment]
Sure! Maybe start here:

https://github.com/basiljs/basil.js/blob/master/includes/core.js#L33
(get a reference for the additional parameter ... )

https://github.com/basiljs/basil.js/blob/master/includes/core.js#L435
(change error handling based on the additional parameter ...)

**Comment by ludzeller** [comment]
Hello Fabian,

Sorry for being a bit slow with these discussions, but I am in the
intense stage of a 3 years research project right now and therefore
cannot contribute a lot to very technical details right now.

It's great that you and Timo want to contribute to the basil.js code
base, so let's think about a good way to achieve this. Basically, since
all the existing core members seem to be rather busy right now, we need
to find an efficient way of working.

Therefore I suggest that you and Timo send us a list of ideas you want
to work on - if you want to hear if we actually want to incorporate your
PRs or would rather see it as something that would reside on a branch
for now. It's best to discuss these things on a case by case level.

Regarding your questions...

"Error Handling": that would be a good thing to start with!

> RE: Better debugging
>
> Instead of
>
> pub.DEBUG = true; pub.errorHandling = true;
>
> I would rather see it as an optional parameter of b.go() ... maybe
> something like
>
> b.go(b.MODEVISIBLE, {debug:true})

I would rather see it as a global flag like pub.ERROR_HANDLING = true;
have to check our global naming conventions.... wouldnt put too much
into the b.go... We had ideas about a cascading, global config file, but
I think we didn't go for it eventually. If you want to design something
in that direction, please make a proposal.

> I would find it super cool to have clean linted basil core files! 👍!
> Please go ahead (or @ludzeller any concerns?)!

I haven't worked with linting in JavaScript and don't know if it's worth
it. If you say that many changes need be introduced, then I
would rather opt for a strict no. The problem is that we cant fully test
everything besides the automatic tests if we introduce a lot of change
and we wouldnt use linting with our students, since we simply use the
ESTK with them. I would always prefer a trusted code base over an
automatically analysed and evaluated one.


Regarding the single vs double quotes:

http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript

> There is no one better solution; however, I would like to argue that
> double quotes may be more desirable at times:
>
> Newcomers will already be familiar with double quotes from their
> language. In English, we must use double quotes " to identify a
> passage of quoted text. If we were to use a single quote ', the
> reader may misinterpret it as a contraction. The other meaning of a
> passage of text surrounded by the ' indicates the 'colloquial'
> meaning. It makes sense to stay consistent with pre-existing
> languages, and this may likely ease the learning and interpretation
> of code. Double quotes eliminate the need to escape apostrophes (as
> in contractions). Consider the string: "I'm going to the mall", vs.
> the otherwise escaped version: 'I\'m going to the mall'. Double
> quotes mean a string in many other languages. When you learn a new
> language like Java or C, double quotes are always used. JSON
> notation is written with double quotes. Nonetheless, as others have
> stated, it is most important to remain consistent.

I think Processing is also always using " in their examples, right?


> RE: #include 'path/to/file' Would it not be better just to use pure
> js browserfy/require for all the basil core development? (Is a js
> file generated with browserfy compatible with Extendscript or not?)

I would leave it as it is right now. Why would you want to get rid of 
the include statements?


I have to say that I am a bit confused why you want to change so much 
about the style and architecture of basil.js immediately in the 
beginning of a collaboration. Benedikt seems to fancy that, but to me 
that seems like a lot of risk just to answer style questions. A better 
way to work together would be to get to know each other by adding small 
elements, modules, etc... another thing that nobody finds time for 
usually is to check the bug reports on github and stack overflow issues...

I think that this would be an easier start. This discussion is having a 
high pace right now without a full voting through all the basiljs 
members. So if you want to be certain that we take your PRs I guess it 
would be easier to contribute to things that are less controversial.

But again, thanks for your time and interest!

Best,
Ludwig

**Comment by fabiantheblind** [comment]
Hi Ludwig,

don't worry about the delay in responses.  

My approach to contribute is and should be.  

- First introduce the new idea.
- Get some feedback from the core members
- implement it, test it, make a PR

### Error handling

I also think that error handling is a good starting point. I'll put it on top of the list. I'll go for a global flag first and then we can still look if it goes into `b.go` or not.

### Linting

About the linting. It is not for the students. It is just a way to get a unified coding style. Most of the linting is not about the function. Just about the code structure. e.g. curly brackets after an if statement or things like that.

### Quotes  

Okay. Let's go for double quotes.  
In Processing single quotes are chars double are strings.  

### Includes  

I don't wan't to get rid of the includes I just suggested moving from # to @ to include things. The hash does not exsist in JS. The @ works fine and allows to run a linter to see if I did some error.  


### Confusion  

Sorry for introducing confusion. I don't want to change everything. These questions are just for getting to know the coding style. If I would add something for error handling I need to know if I could use a codeformatting tool or not because the changes are in the core.js.
