### ISSUE TITLE
Enabling code linting? 

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#34]
When writing scripts I normally use [eslint](http://eslint.org/) with the [Sublime linter package](https://packagecontrol.io/packages/SublimeLinter-contrib-eslint) for it. I also use the [Sublime Text CodeFormatter](https://packagecontrol.io/packages/CodeFormatter). Together they make up a strict and continuous coding style. Now a problem for eslint is the ExtendScript `#include 'path/to/file'` statement. It breaks the parsing. Fortunately there is an undocumented feature in ExtendScript for a different include statement:   

```
//@include 'path/to/file';
```

Or

```
// @include 'path/to/file';
```

Or even

```
//@include 'path/to/file';
```

Also the target application can be set like this. 

```
//@target 'InDesign';
```

This would allow:  
- to run eslint against user scripts
- to run eslint against the Basil source
- to enforce a strict coding style by adding a .eslintrc to the repo which contains rules suited for Basil. 

The next step would be running eslint against the whole project(examples and core). **Be aware that this might change a lot of the current formatting.** So I would do that but only if you guys want this to happen. 

First question for doing this is:
- single or double quotes? (It's some kind of religion 😏) I use single quotes. Throughout Basil there are double quotes. Single quotes make embedding double quotes for messages much easier. 
## How to approach the refactoring?

I think the best way would be formatting it file by file and test if nothing breaks. 

I would create a PR for each file.

**Comment by fabiantheblind** [comment]
I did run eslint against the whole basil folder. Here is the result as HTML: 
https://dl.dropboxusercontent.com/u/1529019/basiljs/basil.eslint.report.html  

This is only a report. No changes where made.

some of the errors can be removed just by disabling the accompanying rules. e.g. no-undef comes from the fact that Basil is split into several files. Also ExtendScript has its `$` and `File` or `Folder` which are unknown to eslint. Others can be fixed just by running a code formatter. The indent for example.  

Others like e.g. "curly" need some manual adjustments.

**Comment by b-g** [comment]
Hi @fabiantheblind,

Many thanks for the effort!!

I would find it super cool to have clean linted basil core files! 👍! Please go ahead (or @ludzeller any concerns?)! 

RE: single vs. double quotes
For me single quotes ... back then we were all new to the js shinny world ... and just went with the java/processing style, which we were familiar.

RE: `#include 'path/to/file'`
Would it not be better just to use pure js browserfy/require for all the basil core development? (Is a js file generated with browserfy compatible with Extendscript or not?)

RE: How to approach the refactoring?
Yes! A PR for each file + while having all tests green ...

Best,
B

PS. We could also have a quick Skype on all this in the next days ... the last thing what I want to do is to slow down a good momentum.

**Comment by fabiantheblind** [comment]
@b-g 

### linting

I'll try to manage it without introducing to many changes. We will see how this turns out. It will be one PR per file.

### Quotes

Single quotes! Single quotes! Single quotes! \o/

### @ vs \# includes 

@vogelino started building a browserify based command line tool for it https://github.com/vogelino/extendscriptr But it is not ready yet to use it on basil. The problem is getting all polyfills together. We converted es6 to es5 and then used different es5 polyfills. The problem is that lots of functions are browser specific and use for example the word `document`. This clashes with InDesign. So we moved to building our own polyfill repo. This will take some more time and testing before using it with basil.

But I started writing a node module that does the bundling of ExtendScript files. Currently I only parse the [AT] not the [HASH] includes but it works. I will parse the [HASH] includes as well. https://github.com/fabiantheblind/extendscript-bundlr I still want to move away from the [HASH] because they break linting in eslint.

**Comment by fabiantheblind** [comment]
@b-g btw I'm up to a Skype session. Tomorrow? Or sometime next week? I'm pretty easy with my schedule right now.
