### ISSUE TITLE
replacing #includes with @includes

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#36]
This should also be an own issue. Does not need any work from your side right now. Just for reference and further discussion. See also #33 #34  
## pros:
- allows usage of linters
- is JS style
## cons:
- would need to refactor all the examples if we want consistency in the whole project

**Comment by trych** [comment]
Alright, my course started last week and I gave the students a custom .zip with the most current basil.js bundled file and example scripts that were all updated to have the lines

    //@includepath "~/Documents/;%USERPROFILE%Documents";
    //@include "basiljs/basil.js";

instead of the old

    #includepath "~/Documents/;%USERPROFILE%Documents";
    #include "basiljs/bundle/basil.js";

along with instructions to put the basil.js at `~/Documents/basiljs/` instead of `~/Documents/bundle/basiljs/`. This all worked pretty well, the `//@` did not cause any issues.

Is there any chance to have a PR pretty soon which replaces the include statements globally and updates the paths to point to `~/Documents/basiljs/`? Then developers could move their repo to basiljs as well. At the moment I would have to always copy the latest version of basil.js there to make scripts with the updated path work.

@fabianmoronzirfas 
I did try to make a global replace of the include paths, however there are instances which are part of your node.js mumbo jumbo that I don't dare to touch and there are also instances which are generated by yuidoc (in the html-files) that I think should not be touched at all, but generated by yuidoc instead. Fabian, could you maybe take care of the replacement of the include statements and the paths? I don't want to mess anything up with the node.js stuff, as I have no idea how this works.

**Comment by fabianmoronzirfas** [comment]
hm. 

- What about the documentation on http://basiljs.ch/
- What about the install scripts

They need to be updated as well if we change the location.

**Comment by ffd8** [comment]
Changing to an //@ requires all/any documentation, tutorials, etc. to be updated. For the benefit of linters? Even though JS style may call for //@, does the realm of InDesign prefer a #?
https://forums.adobe.com/thread/421320
https://forums.adobe.com/thread/290259

Does the //@ format not look like commented out code?

Perhaps, once basil.js is delivered as a single packaged script (for 2.0) then the location could be modified to "basiljs/basiljs.js" (or wherever locally if preferred by user).

**Comment by trych** [comment]
Yes, but wasn't it the plan to change the location?

You suggested it [here](https://github.com/basiljs/basil.js/pull/93#issuecomment-247542466) and @b-g approved.

The documentation is out of sync with the github master anyways, so this is another issue which becomes urgent now (and has [its own dedicated issue](https://github.com/basiljs/basil.js/issues/61) already). If yuidoc is still used then somebody needs to rebuild things, which changes a whole lot of stuff, since yuidoc has been substantially updated. Also the yuidoc stuff then needs to be moved to the actual basiljs.ch website. Is anybody in charge of that at the moment?

**Comment by fabianmoronzirfas** [comment]
About the //@ vs # you know my preferences. I would go for //@ 

About the location. This should be done in one move with updating the docs and the site. But @trych is right. There are new features that should be added to the docs. 

I can change the scripts and tutorials with some regex no biggy but the docs need some love as well.

**Comment by fabianmoronzirfas** [comment]
Damn. I need to delete that commit. There are some changes that don't should be there.

**Comment by trych** [comment]
> Changing to an //@ requires all/any documentation, tutorials, etc. to be updated.

They all need to be updated anyways since the path is going to change from `~/Documents/basiljs/bundle/` to just `~/Documents/basiljs/` as decided [here](https://github.com/basiljs/basil.js/pull/93#issuecomment-247542466). I think a linter would really help to keep the library clean and consistent and I had problems with linters in the past for exactly this `#include` statement.

> Does the //@ format not look like commented out code?

I think so, but I also think this should not matter much to the average Joe starting learning basil.js or coding. I remember when I started these two include lines were just some gibberish to me which I always just needed to copy along to make it work. I think it would not really matter for the end user if it starts with `#` or with `//@`.

> docs need some love as well

Yes, I started the seminar now with a basil.js file that for example contains a `b.gradient()` method and the `gradient.jsx` example script, but without any documentation for it (except library itself), it would be very nice, if we could quickly find a (temporary?) solution. I guess Fabian will run into the same situation when his seminar starts?

**Comment by ffd8** [comment]
Sure the plan to change the location was mentioned but in combination with it becoming a single script and thus no longer needing the bundle. The question is, does single script release wait until 2.0 or already 1.0.11? It's a pretty big change in structure.

The website reference is indeed slowly falling out of date from these new features. It's based on a data.json doc, that is built from the yuidoc files. @ludzeller had created both the yuidoc and a json, which I have a script for formatting for the web. I'll get in touch with him about that workflow so we can keep it up to date. 

Does running code with an #include break the linting process completely or just that line throws a red flag? I'm doubtful that many design students starting to code for the first time will be using linters. I don't want to argue only for the sake of keeping it like it is, but to also keep best compatibility with InDesign. Can you also write //@targetengine "loop"? If that requires a # from ESTK, then it would be odd to use a mixture of the two.

**Comment by fabianmoronzirfas** [comment]
Using # stops linters from execution. We can use @ target and @ targetengine

**Comment by trych** [comment]
> I'm doubtful that many design students starting to code for the first time will be using linters.

Correct me, if I'm wrong, I thought this was rather *for us* to lint all files on the developing side (like also the example scripts) and so on and not so much for students using linters. Of course students wouldn't use linters, but we as developers could really make good use of one (whitespace issues, consistent formatting etc.).

**Comment by fabianmoronzirfas** [comment]
> Sure the plan to change the location was mentioned but in combination with it becoming a single script and thus no longer needing the bundle. The question is, does single script release wait until 2.0 or already 1.0.11? It's a pretty big change in structure.

I would release the single script version now with the next semver. It introduces no changes to the user and is still compatible with all the documentation. Should be a minor update 1.1.0 not a patch version. 

Moving the file and also the removing of `b.`  is for 2.0. This needs to go hand in hand with the docs and site update

**Comment by ffd8** [comment]
Sure then it can change to //@
Just wanted to be certain it was worth the mod to existing docs.

**Comment by trych** [comment]
@fabianmoronzirfas what is the status on the linting? I know you have linted the source files, but can we use the linter already? If so, how? Could you give a short explanation in the wiki?

I was making an PR where I changed two example scripts, but since I don't know how to lint with your linting setup these files stay unlinted for now.

**Comment by fabianmoronzirfas** [comment]
Hey @trych I'm caught up in the Quito aftermath. I currently have no time. But a quick setup guide would be in sublime:  

- install sublime linter
- install sublime linter eslint (needs eslint in your path - might also work with a local version)
- install sublime eslint formatter 

If everything works right you should be good to go.

**Comment by trych** [comment]
Hi @fabianmoronzirfas, no stress!

I will try to follow the steps and get it set up. Thanks!

**Comment by trych** [comment]
I cannot for the life of me figure out how to get this to work. I am trying to run the formatter and it gives me the error message

`Error: Cannot find module '/usr/local/bin/eslint'`

I did a `which eslint` in the terminal and found out it actually sits at `/Users/trych/.npm-packages/bin/eslint`. I then went ahead and changed the `paths` setting in the Sublime-Linter user settings to

```js
"paths": {
     "linux": [],
     "osx": [
         "~/.npm-packages/bin"
     ],
     "windows": []
}
```
Still, the error keeps coming up. Anybody any idea, what's going on?

**Comment by fabianmoronzirfas** [comment]
How is your node installed? From pkg or via brew? Did you try adding the whole path to eslint. Not the ~ one? Did you try the path with eslint in it? Can you run eslint from command line? What about other globally installed npm tools? Do they work?

**Comment by trych** [comment]
> How is your node installed? From pkg or via brew?

I do not quite remember, is there any way to check?

> Did you try adding the whole path to eslint. Not the ~ one?

Yes, that's what I tried first, did not work.

> Did you try the path with eslint in it?

Did not work either.

> Can you run eslint from command line?

Yes, from the command line I can run it.

I just realized that eslint does not show up in my SublimeLinter linter list when I do `SublimeLinter: Enable Linter`. Is it supposed to show up there?

**Comment by fabianmoronzirfas** [comment]
Yes it should be there. You need sublime linter and the sublime linter eslint package. These are two separate packages

**Comment by fabianmoronzirfas** [comment]
To check if you installed node via brew run  

      brew list

If you installed node via brew it should be in there

**Comment by trych** [comment]
Ok, sorry, I installed the wrong eslint (there were two different ones in PackageControl). Now the sublime linter eslint package works. However, I cannot get the ESLintFormatter to work. It seems to find eslint after I changed the paths (before it gave me the same error as the other package), but it does not do anything.

How is it supposed to work? I do "Format this file" and then it automatically changes the opened file according to the specified rules?

I mean I can do manual line-by-line linting now, but it would be much nicer of course, if I could format entire files.

Btw. brew list returns that `node` was installed via brew, but `npm` does not show up in this list. Is it supposed to? I seem to remember that I also installed node via pkg recently, maybe that messed something up as it apparently was installed via brew earlier?

**Comment by trych** [comment]
Also, I just saw that the docs state

> ESLint (with autoformatting) must be installed on your system

What does the part "with autoformatting" mean? Is that something I need to turn on/specially install?

**Comment by fabianmoronzirfas** [comment]
> Btw. brew list returns that node was installed via brew, but npm does not show up in this list. Is it supposed to?  

Yes That is normal.

 > I seem to remember that I also installed node via pkg recently, maybe that messed something up as it apparently was installed via brew earlier?   

Having both installed is not good. You should remove the one installed via pkg und just go for the brew one (easier to update).

> How is it supposed to work? I do "Format this file" and then it automatically changes the opened file according to the specified rules?  

The formatter should be able to format "on save" based on the current .eslintrc. I think you have to set this in the formatters settings. These are my user settings

    {"format_on_save": true}
