### ISSUE TITLE
Image placing with only x coordinate does not work as expected

### ISSUE THREAD

**Issue by fabiantheblind** [basiljs/basil.js#49]
As mentioned in issue #26 placing an image file (or .ai) does not work when using just the `x` coordinate as parameter.  

    #includepath "~/Documents/;%USERPROFILE%Documents";
    #include "basiljs/bundle/basil.js";
    function draw() {
      //b.image("test.png",0); // does not work as expected 0 should be x of newly created container
      b.image("test.ai", 0, 0, 100, 100); // works as expected
      var rect = b.rect(0, 100, 100, 100); // create a rectangle to place the image in
      b.image("test.ai", rect); // works as expected
    }
    b.go();

Attached is a test setup for this.  
[basil-place-ai-file.zip](https://github.com/basiljs/basil.js/files/349593/basil-place-ai-file.zip)

**Comment by trych** [comment]
@fabiantheblind When providing test setups with InDesign files, could you always provide the .idml file instead of (or additionally to) an .indd file? That way you make sure, that also we CS6 people can open it. Thanks! :)

**Comment by trych** [comment]
I don't think `b.image("img.png", x)` is even supposed to work.

The possible argument options are

`b.image("img.png", shape);`

`b.image("img.png", x, y);`

`b.image("img.png", x, y, w, h);`

But I have to admit the method doc is not very clear on that. The reason why `y` is optional in the description `b.image(img, x, [y], [w], [h])` is not because `b.image(img, x) is a valid option, but because y is not a required argument with `b.image(img, shape)`. I think that leads to the misunderstanding, that `b.image(img, x)` is possible.

Still, there is a bug, there should be a basil.js-error with an understandable error message thrown when you do `b.image(img, x)` and not a InDesign error that nobody understands.

Also the description should be made more clear that you have the three options that I named above.

**Comment by fabiantheblind** [comment]
😋 Thanks. Also duh?! What would be a function with only x coordinate bring in this case. So this issue is for the docs. About the idml. You are totally right.
