### ISSUE TITLE
update yuidoc 

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#61]
As seen in #60 yuidoc needs an update. How is it integrated into the build of the website?

**Comment by trych** [comment]
Specifically, (as I just tried it) there seem to be substantial updates for yuidoc, since it was last used with basil.js, so it seems to build the api html files and related files differently now than it did two years ago, which results in a lot of additions and deletions upon the first "rebuild" after such a long time.
Could someone, who is responsible for building the final website (I remember @ludzeller [was updating the docs a while ago](http://stackoverflow.com/a/22297455/3399765)) maybe do this first rebuild to check that everything still works, or alternatively let us know, what to do.

Thanks! :)

**Comment by trych** [comment]
I guess we can still already work on updates and improvements on the actual documentation of the methods (in the includes/core.js files for example, I mean) and just leave out the generating of the yuidocs for now?

**Comment by fabiantheblind** [comment]
Yes. I would leave the doc generation alone for the time being. Concentrate on the features and testing for now.

**Comment by fabianmoronzirfas** [comment]
I think we can close this one. Since we don't use yuidoc anymore.
