### ISSUE TITLE
git line endings error

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#88]
Can we reproduce the error @trych had in issue #62 [comment](https://github.com/basiljs/basil.js/pull/62#issuecomment-233915649)?  

Maybe adding a .gitattributes file can fix that problem

http://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes-file

.gitattributes

```
* text=auto
```

**Comment by b-g** [comment]
There is already an https://github.com/basiljs/basil.js/blob/master/.gitattributes ... no idea.

Can we not solve this with an editorconfig?
eg. https://github.com/generative-design/Code-Package-p5.js/blob/master/.editorconfig

**Comment by trych** [comment]
This is not really an issue to "reproduce", the issue is (or rather was)  in the encoding of the file itself. And it got introduced with a certain commit, in this case [this one](https://github.com/basiljs/basil.js/commit/6397baf3bc30b2d3f9cabe948895c706392cc1b3#diff-caea5719979560d43b1a32a31a905f5d). As you can see, before committing the file's encoding was fine, with the commit the line endings were changed, so it was only one line after that.

All the files could be fixed by the method that I linked in the original thread, I just don't even know which files need to be fixed if any.

And how does the issue actually get introduced? When somebody saves his .jsx file in ESTK?

**Comment by fabiantheblind** [comment]
> There is already an https://github.com/basiljs/basil.js/blob/master/.gitattributes ... no idea.  
So this didn't prevent the change of the LFs

I'll try to reproduce this. But it has a lower priority

**Comment by trych** [comment]
>There is already an https://github.com/basiljs/basil.js/blob/master/.gitattributes ... no idea.

Actually this was commited 4 days _after_ the erroneous commit that messed up the line endings. So it might very well be working already. In this case we just need to figure out, if there are any files that are still messed up and simply fix them manually once.

**Comment by fabianmoronzirfas** [comment]
This was fixed by removing all files with win `\r\n` line feeds. Might come up again. Still closing.
